### ISSUE TITLE
Error: "Folder regex: This folder does not allow uploads!"

### ISSUE THREAD

**Issue by newnottakename** [ReadBox/readbox#4] opened 2015-03-07 14:05 UTC
When trying to upload a pdf called: "Samenvatting Eigenvectoren" to "http://readbox.wol.ph/readbox/list/Q3 Dropbox/Propedeuse (Eerste jaar)/Lineaire Algebra (TI1206M) Q3" it returns an error saying: "Folder regex: This folder does not allow uploads!". I do not know if this is intended behaviour. If it is please add some information. Thanks!

**Comment by WoLpH** [comment] 2015-03-07 22:18
It's definitely not intended behaviour, the problem is that my Dropbox account ran out of diskspace...

Should be fixed now :)

**Closed by WoLpH** 2015-03-07 22:18 UTC
